version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.${ENV:-dev}
    container_name: go_api
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.${ENV:-dev}
    container_name: react_frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"  # Defaults to 3000 in dev, 80 in prod
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/messages
    depends_on:
      - backend

