# Stage 1: Build the Go application
FROM golang:1.18-alpine AS builder

# Build the binary with static linking
# RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app

# Stage 2: Minimal image for production
FROM scratch

